#!/bin/bash

# Call to prevent stopping user container
# Write "stopdockerwatch" to sacred_proc_file
#
# Created by Bryzgalov Peter
# Copyright (c) 2013-2015 Riken AICS. All rights reserved

version="0.45"

# This will be replaced by createuset.sh
initvariables

echo "$0 v$version"
exec 20<>$stop_file
flock -x -w 2 20
echo "1" > $stop_file
flock -u 20
echo "Enter nostop state"