#!/bin/bash

# Call to prevent stopping user container
# Write "stopdockerwatch" to sacred_proc_file
#
# Created by Bryzgalov Peter
# Copyright (c) 2013-2015 Riken AICS. All rights reserved

version="0.34a01"

# This will be replaced by createuset.sh
initvariables

echo "$0 v$version $stop_file"
exec 20<>$stop_file
flock -x -w 2 20
echo "0" > $stop_file
flock -u 20
echo "Exit nostop state"
# Start dockerwatch.sh
echo "Starting dockerwatch"
dockerwatch=(/dockerwatch.sh $counter_file $stop_file)
eval "nohup ${dockerwatch[@]}" >>${basename}.log 2>&1 &