#!/bin/sh

# Call to stop user container immediately
#  
# Created by Bryzgalov Peter on 2014/01/31
# Copyright (c) 2013-2014 Riken AICS. All rights reserved

# Counter files
counter_file="/tmp/dockeriaas_cc"
stop_file="/tmp/dockeriaas_nostop"
# Log file name
basename="/logs/container"

echo "Stopping container"
echo "0" > counter_file
echo "0" > stop_file

kill 1