#!/bin/sh

# Call to stop user container immediately
#  
# Created by Bryzgalov Peter on 2014/01/31
# Copyright (c) 2013-2015 Riken AICS. All rights reserved

version="0.34a01"

# This will be replaced by createuset.sh
initvariables

echo "Stopping container"
echo "0" > counter_file
echo "0" > stop_file

kill 1